---
name: Release archive

'on':
  push:
    paths-ignore:
      - '**/*.md'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"
    branches:
      - 'build-*'
  schedule:
    - cron: '05 00 01 * *'
  workflow_dispatch:

concurrency:
  # https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/v') || github.ref != 'refs/heads/development' }}

permissions:
  contents: read
  packages: read

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: 18.19.0
  TS_FILENAME: "bridge"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          yarn config set //npm.pkg.github.com/download/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          yarn config set @tari-project:registry https://npm.pkg.github.com
          yarn --frozen-lockfile

      - name: Build
        run: |
          npm run build

      - name: Debug files
        shell: bash
        run: |
          # set -xo pipefail
          ls -alht

      - name: Artifact upload for Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TS_FILENAME }}_archive_unreleased
          path: "out"

      - name: Archive and Checksum Binaries
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          echo "Archive ${{ env.TS_FILENAME }} too ${{ env.TS_FILENAME }}.zip"
          cd "out"
          7z a "${{ env.TS_FILENAME }}.zip" *
          echo "Compute archive shasum"
          ${SHARUN} "${{ env.TS_FILENAME }}.zip" >> "${{ env.TS_FILENAME }}.zip.sha256"
          echo "Show the shasum"
          cat "${{ env.TS_FILENAME }}.zip.sha256"
          echo "Checksum verification archive is "
          ${SHARUN} --check "${{ env.TS_FILENAME }}.zip.sha256"
